[package]
name = "cutenet-macros"

edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = {version = "2.0", features = ["extra-traits"]}
